DROP TABLE IF EXISTS user_student;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS test_score;
DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS school;
DROP TABLE IF EXISTS district;