// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type District struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type School struct {
	ID         int64         `json:"id"`
	DistrictID sql.NullInt64 `json:"districtID"`
	Name       string        `json:"name"`
	CreatedAt  time.Time     `json:"createdAt"`
}

type Student struct {
	ID         int64         `json:"id"`
	SchoolID   sql.NullInt64 `json:"schoolID"`
	FirstName  string        `json:"firstName"`
	LastName   string        `json:"lastName"`
	Identifier string        `json:"identifier"`
	CreatedAt  time.Time     `json:"createdAt"`
}

type Test struct {
	ID         int64          `json:"id"`
	DistrictID sql.NullInt64  `json:"districtID"`
	Subject    sql.NullString `json:"subject"`
	TestDate   time.Time      `json:"testDate"`
	Name       string         `json:"name"`
}

type TestScore struct {
	TestID    sql.NullInt64 `json:"testID"`
	StudentID sql.NullInt64 `json:"studentID"`
	TestDate  time.Time     `json:"testDate"`
	Score     string        `json:"score"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashedPassword"`
	FullName          string    `json:"fullName"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
	CreatedAt         time.Time `json:"createdAt"`
}

type UserStudent struct {
	UserID    sql.NullInt64 `json:"userID"`
	StudentID sql.NullInt64 `json:"studentID"`
}
