// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateDistrict(ctx context.Context, name string) (District, error)
	CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDistrict(ctx context.Context, id int64) error
	DeleteSchool(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllDistricts(ctx context.Context, arg GetAllDistrictsParams) ([]District, error)
	GetAllSchools(ctx context.Context, arg GetAllSchoolsParams) ([]School, error)
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error)
	GetDistrict(ctx context.Context, id int64) (District, error)
	GetSchool(ctx context.Context, id int64) (School, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) (District, error)
	UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
